# Generated by Django 3.2.4 on 2023-09-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True)),
                ('category_picture', models.ImageField(null=True, upload_to='static/category/')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, null=True)),
                ('city_picture', models.ImageField(null=True, upload_to='static/city/')),
            ],
        ),
        migrations.CreateModel(
            name='mynews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_picture', models.ImageField(null=True, upload_to='static/news/')),
                ('news_headlines', models.TextField()),
                ('news_discription', models.TextField()),
                ('news_date', models.DateField()),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('news_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
            ],
        ),
    ]
