# Generated by Django 3.2.4 on 2023-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_vnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnews',
            name='vlink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
