# Generated by Django 3.2.4 on 2023-09-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_vnews_vlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('job_link', models.CharField(max_length=200, null=True)),
                ('job_picture', models.ImageField(null=True, upload_to='static/jobs')),
            ],
        ),
    ]
